### ISSUE TITLE
Fix access checking logic for sync test

### ISSUE THREAD

**Issue by amcgee** [dhis2/android-settings-app#31]
See [this PR comment](https://github.com/dhis2/android-settings-app/pull/29#discussion_r419769670).  If we are checking for **read and write data access** we need to check that ONLY the first two characters are `rw`.  `--rw----` is also a valid access string which contains `rw` but does NOT grant data access.

**Comment by Sharmyn28** [comment]
Hi @amcgee I'm thinking about this to solve it:

```
checkAccess = (elementArray, accessIDList) => {
        elementArray.forEach(element => {
            if (element.publicAccess.indexOf('rw') === 0) {
                accessIDList.push(element)
            }
        })

        return accessIDList
    }
```

**Comment by Sharmyn28** [comment]
By doing this we check if `rw` is at the beginning of the string.

**Comment by amcgee** [comment]
@Sharmyn28 that should work.  Another way to do the same would be `if (element.publicAccess.substring(0, 2) === 'rw')`, but the `indexOf` method looks fine too!

**Comment by Sharmyn28** [comment]
great! I'll create a PR with this :)
