### ISSUE TITLE
Confirm wording: First launch dialog

### ISSUE THREAD

**Issue by Sharmyn28** [dhis2/android-settings-app#49]
This should be "You are not authorized to configure Android settings, please contact a DHIS2 system administrator." (cc @cooper-joe to improve on my wording)

_Originally posted by @amcgee in https://github.com/dhis2/android-settings-app/pull/47_

**Comment by cooper-joe** [comment]
If this applies to the entire app and all of its options, I think we go really simple:

"You don't have access to this app. Contact your DHIS2 system administrator to fix this problem."
